### ISSUE TITLE
ユーザーネーム機能

### ISSUE THREAD

**Issue by ywenli** [ywenli/techpitgram#4]
# これは？

ユーザーネームの登録、表示、編集機能を作ります。

## todo 

登録

- [x] ユーザーネーム用のフォームを追加
- [x] ユーザーネーム用のカラム作成 notNull
- [x] ユーザーネーム保存のためにパラメーターを追加
- [x] validationを追加 uniqueness: true

表示

- [x] ビューファイル users/show.html.haml編集

編集

- [x] 新しいユーザーネームを入力するフォームを追加 registrations/edit.html.haml
- [x] usernameカラムを更新するためにappliccation_controller.rb にパラメーターを追加

## 備考

なし
